# Generated by Django 5.0.4 on 2024-05-22 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_result_penalty_alter_result_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
