# Generated by Django 5.0.4 on 2024-05-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_room_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
    ]
