# Generated by Django 5.0.4 on 2024-05-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_room_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
